apiVersion: v1
kind: Service
metadata:
  name: matches-service
  labels:
    app: matches
spec:
  type: NodePort
  selector:
    app: matches
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080